    SELECT *
      FROM PCAP_ATTACK
 LEFT JOIN PCAP_ATTACK_PACKET
        ON PCAP_ATTACK.id = PCAP_ATTACK_PACKET.attack_id
 LEFT JOIN PCAP_PACKET
        ON PCAP_PACKET.id = PCAP_ATTACK_PACKET.packet_id
 LEFT JOIN PCAP_IP
        ON PCAP_PACKET.ip_id = PCAP_IP.id
     LIMIT 100