DROP TABLE IF EXISTS DNS_ANALYSIS;

CREATE TABLE DNS_ANALYSIS (
	id INTEGER NOT NULL,
	year INTEGER NOT NULL,
	period INTEGER NOT NULL,
	requests_per_attack INTEGER NOT NULL,
	query_id INTEGER NOT NULL,
  tempo_final TEXT NOT NULL,
  ip TEXT NOT NULL
);
