DROP TABLE IF EXISTS DNS_ANALYSIS;

-- id INTEGER PRIMARY KEY AUTOINCREMENT,
CREATE TABLE DNS_ANALYSIS (
	year INTEGER NOT NULL,
	period INTEGER NOT NULL,
	qname VARCHAR(255),
	qtype VARCHAR(255),
	count INTEGER NOT NULL
);
