---
title: "mesma_vitima_distancia.rmd"
author: "Rafilx"
date: "`r Sys.Date()`"
output: html_document
---

```{r echo=FALSE}
library('RSQLite')
library('ggplot2')
library(DBI)
options("scipen"=100, "digits"=4)
library(dplyr)
require(gridExtra)
library(tibble)
library(tidyr)
library(viridis)
library(lubridate)
library(blob)
library(scales)
library(ggrepel)
# library(ggpubr)
# install.packages("ggpubr")
# library("dplyr.teradata")
```

```{r echo=FALSE}
addUnits <- function(n) {
  labels <- ifelse(n < 1000, n, # less than thousands
    ifelse(n < 1e6, paste0(round(n/1e3), 'k'), # in thousands
      ifelse(n < 1e9, paste0(round(n/1e6, 1), 'M'), # in millions
        ifelse(n < 1e12, paste0(round(n/1e9, 2), 'B'), # in billions
          ifelse(n < 1e15, paste0(round(n/1e12, 3), 'T'), # in trillions
  'too big!')))))
  return(labels)
}

addUnitMeses <- function(n){
  return(paste(n, "meses"))
}

minutes = 60
hours = minutes * 60
days = hours * 24
months = days * 30
years = months * 12

addUnitsHours <- function(n) {
  labels <- ifelse(n < minutes, n, # less than 60
    ifelse(n < hours, paste0(round(n/minutes), 'Min'), # in hours
      ifelse(n < months, paste0(round(n/hours, 1), 'Horas'), # in millions
        ifelse(n < years, paste0(round(n/months, 2), 'Meses'), # in billions
          ifelse(n < 1e15, paste0(round(n/years, 3), 'Anos'), # in trillions
  'too big!')))))
  return(labels)
}


labelBiggerThan9 <- function(n){
  labels <- ifelse(n > 9, paste(round(n, 2), "%"), "")
  return(labels)
}

add_percentage <- function(n){
  labels <- paste(round(n, 2), "%")
  return(labels)
}


safe_colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499",
                             "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")
minimum_percentage_as_others = 5
decimals_digits = 2

plots_path = "/home/rafilx/projects/github.com/RafilxTenfen/master/Obelheiro/pesquisa/honeypot_data/rstudio/v1-sqldump-thiago/plots"
```


```{r}
vitima_db_mix_protocol <- dbConnect(RSQLite::SQLite(), dbname="../../db/database-2022-05-11/mix_protocol.sqlite")

vitima_data_mix_protocol_unfetch <-dbSendQuery(vitima_db_mix_protocol, "
  SELECT *, CAST(CAST(year AS text) || CAST(period AS text) as integer) as year_period
    FROM (
      SELECT *,  strftime(\"%Y\", tempo_inicio) as year, ((strftime(\"%m\", tempo_final) - 1) / 3) + 1 AS period
        FROM MIX_PROTOCOL
    )
   WHERE year_period >= 20184 AND
         year_period <= 20221 AND
         requests_per_attack >= 5
")
vitima_data_mix_protocol <- fetch(vitima_data_mix_protocol_unfetch)

dbDisconnect(vitima_db_mix_protocol)
```


- Formatando os timestamp

```{r}
vitima_data_mix_protocol['tempo_final_cast'] = as.POSIXct(vitima_data_mix_protocol[['tempo_final']], format = "%Y-%m-%d %H:%M:%S")
vitima_data_mix_protocol['tempo_inicio_cast'] = as.POSIXct(vitima_data_mix_protocol[['tempo_inicio']], format = "%Y-%m-%d %H:%M:%S")
```

- Ordena e adiciona a nova coluna

```{r}
vitima_data_ordered = vitima_data_mix_protocol %>%
  arrange(desc(vitima_ip), tempo_inicio_cast) 

vitima_data_ordered['time_diff'] = 0

vitima_data_ordered_selected = vitima_data_ordered %>%
  select(vitima_ip, attack_protocol, requests_per_attack, year_period, time_diff, tempo_inicio_cast, tempo_final_cast, raw_payload)
```

- Popula a coluna com a diferença

```{r}

# if it is grouped by victim
pos_time_inicio = 4
pos_time_fim = 5
pos_time_diff = 3

# data_ordered_selected[[pos_time_fim]][12321]

vitimas_data = vitima_data_ordered_selected %>%
  group_by(vitima_ip, attack_protocol) %>%
  group_modify(~{
    count = count(.x)$n
    if (count > 1) {
      for (i in 2:count) {
        .x[[pos_time_diff]][i] = as.numeric(.x[[pos_time_inicio]][i] - .x[[pos_time_fim]][i-1], units="secs")
      }
    }
    .x
  })


saveRDS(vitimas_data, file = "vitimas_data_time_diff_vitima&protocol.Rds")
```


```{r}

vitimas_data_selected = vitimas_data %>%
  # filter(time_diff != 0) %>%
  arrange(desc(vitima_ip)) %>%
  select(vitima_ip, attack_protocol, requests_per_attack, time_diff, year_period, tempo_inicio_cast, tempo_final_cast)
```

- Plot vitimas histograma

```{r fig.width = 12}

vitimas_data_selected %>%
  filter(time_diff >= 0) %>%
  mutate(year_period = paste(substr(year_period, 0, 4), substr(year_period, 5, 5), sep = "/")) %>%
  ggplot( aes(x=time_diff)) +
  geom_histogram(bins = 60, fill='blue', color ='black') +
  # geom_text(aes(label = addUnits(time_diff),  vjust = -0.25)) +
  # scale_fill_viridis(discrete=TRUE) +
  scale_y_continuous(labels = addUnits) +
  theme(
    plot.title = element_text(size = 22),
    axis.title = element_text(size = 18),
    strip.text = element_text(size = 16),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 18),
  ) +
  ylab("intervalo entre ataques para uma mesma vitima") +
  xlab("Período (Trimestre)")
```

```{r}
vitimas_data_selected %>%
  filter(time_diff < 0)

vitimas_data_selected %>%
  filter(vitima_ip == "99.47.21.54") %>%
  arrange(tempo_inicio_cast)

vitimas_filtered = vitimas_data_selected %>%
  filter(time_diff > 0) 

plot.ecdf(vitimas_filtered$time_diff, )


summary(vitimas_filtered)

vitimas_time_diff_less60 = vitimas_filtered %>%
  filter(time_diff <= 60) %>%
  group_by(vitima_ip, attack_protocol) %>%
  summarise(qnt = n()) %>%
  arrange(desc(qnt))
  

vitimas_time_diff_less60
  
summary(vitimas_time_diff_less60)

vitimas_data_selected %>%
  filter(time_diff > 60) %>%
  filter(time_diff <= 3600)
```


- Histograma de intervalo de tempo entre 61sec e 3600 sec

```{r fig.width = 12}

vitimas_data_selected %>%
  filter(time_diff > 60) %>%
  filter(time_diff <= 3600) %>%
  ggplot( aes(x=time_diff)) +
  geom_histogram(bins = 60, fill='blue', color ='black') +
  # geom_text(aes(label = addUnits(time_diff))) +
  scale_y_continuous(labels = addUnits) +
  theme(
    plot.title = element_text(size = 22),
    axis.title = element_text(size = 18),
    strip.text = element_text(size = 16),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 18),
  ) +
  ylab("Quantidade") +
  xlab("Segundos de intervalo entre ataques de mesma vitima+protocolo") + 
  ggtitle("Vitima + Protocolo = Intervalo entre 61 e 3600 segundos")
```



- for
```{r}
# pos_vitima = 6
# count = count(data_ordered)$n
# time_diff = 0
# pos_time_inicio = 11
# pos_time_fim = 12
# pos_time_diff = 13

# for (i in 2:count) {
#   # cur_vitima = data_ordered[[pos_vitima]][i]
#   # previous_vitima = data_ordered[[pos_vitima]][i-1]
#   
#   if (data_ordered[[pos_vitima]][i] == data_ordered[[pos_vitima]][i-1]) {
#     # previous_time = data_ordered[[pos_time_fim]][i-1]
#     # cur_time = data_ordered[[pos_time_inicio]][i]  
#     data_ordered[[pos_time_diff]][i] = data_ordered[[pos_time_inicio]][i]  - data_ordered[[pos_time_fim]][i-1]
#   } 
# }
```